/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread */

#ifndef _Included_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
#define _Included_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_MIN_PRIORITY
#define com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_MIN_PRIORITY 1L
#undef com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_NORM_PRIORITY
#define com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_NORM_PRIORITY 5L
#undef com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_MAX_PRIORITY
#define com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_MAX_PRIORITY 10L
#undef com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_SmsPrice
#define com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_SmsPrice 0.1
/*
 * Class:     com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
 * Method:    Rank
 * Signature: ([DII)I
 */
JNIEXPORT jint JNICALL Java_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_Rank
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
 * Method:    Transform
 * Signature: ([DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_Transform
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
 * Method:    Inverse
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_Inverse
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread
 * Method:    MultiMatrix
 * Signature: ([DI[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_archermind_callstat_PhonebillCaculate_PhonebillCaculateThread_MultiMatrix
  (JNIEnv *, jobject, jdoubleArray, jint, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
